kind: Service
apiVersion: v1
metadata:
  name: grafana
  namespace: monitoramento
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP