kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: monitoramento
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP